# celebrities.py

data = [
    {
        "name": "Cristiano Ronaldo",
        "followers": 630,
        "description": "Footballer",
        "country": "Portugal",
    },
    {
        "name": "Lionel Messi",
        "followers": 520,
        "description": "Footballer",
        "country": "Argentina",
    },
    {
        "name": "Selena Gomez",
        "followers": 430,
        "description": "Singer & Actress",
        "country": "USA",
    },
    {
        "name": "Kylie Jenner",
        "followers": 400,
        "description": "Model & Businesswoman",
        "country": "USA",
    },
    {
        "name": "Dwayne Johnson",
        "followers": 395,
        "description": "Actor & Wrestler",
        "country": "USA",
    },
    {
        "name": "Kim Kardashian",
        "followers": 365,
        "description": "Media Personality",
        "country": "USA",
    },
    {
        "name": "Virat Kohli",
        "followers": 275,
        "description": "Cricketer",
        "country": "India",
    },
    {"name": "Beyoncé", "followers": 320, "description": "Singer", "country": "USA"},
    {
        "name": "Taylor Swift",
        "followers": 270,
        "description": "Singer & Songwriter",
        "country": "USA",
    },
    {
        "name": "Justin Bieber",
        "followers": 290,
        "description": "Singer",
        "country": "Canada",
    },
    {
        "name": "Narendra Modi",
        "followers": 90,
        "description": "Prime Minister",
        "country": "India",
    },
    {
        "name": "Zendaya",
        "followers": 190,
        "description": "Actress",
        "country": "USA",
    },
    {
        "name": "Shah Rukh Khan",
        "followers": 45,
        "description": "Actor",
        "country": "India",
    },
    {
        "name": "Billie Eilish",
        "followers": 110,
        "description": "Singer",
        "country": "USA",
    },
    {
        "name": "Elon Musk",
        "followers": 190,
        "description": "Entrepreneur",
        "country": "USA",
    },
    {
        "name": "Emma Watson",
        "followers": 75,
        "description": "Actress",
        "country": "UK",
    },
    {
        "name": "Jungkook",
        "followers": 90,
        "description": "Singer (BTS)",
        "country": "South Korea",
    },
    {
        "name": "Khabane Lame",
        "followers": 80,
        "description": "Content Creator",
        "country": "Italy",
    },
    {
        "name": "Gigi Hadid",
        "followers": 80,
        "description": "Model",
        "country": "USA",
    },
    {
        "name": "Hrithik Roshan",
        "followers": 45,
        "description": "Actor",
        "country": "India",
    },
    {
        "name": "Robert Downey Jr.",
        "followers": 100,
        "description": "Actor",
        "country": "USA",
    },
    {
        "name": "Ariana Grande",
        "followers": 380,
        "description": "Singer",
        "country": "USA",
    },
    {
        "name": "Katy Perry",
        "followers": 200,
        "description": "Singer",
        "country": "USA",
    },
    {
        "name": "David Beckham",
        "followers": 87,
        "description": "Footballer",
        "country": "UK",
    },
    {
        "name": "Tom Holland",
        "followers": 80,
        "description": "Actor",
        "country": "UK",
    },
    {
        "name": "Alia Bhatt",
        "followers": 90,
        "description": "Actress",
        "country": "India",
    },
    {
        "name": "Ranveer Singh",
        "followers": 50,
        "description": "Actor",
        "country": "India",
    },
    {
        "name": "BLACKPINK Lisa",
        "followers": 100,
        "description": "Singer (BLACKPINK)",
        "country": "Thailand",
    },
    {
        "name": "MrBeast",
        "followers": 50,
        "description": "YouTuber",
        "country": "USA",
    },
    {
        "name": "LeBron James",
        "followers": 170,
        "description": "Basketball Player",
        "country": "USA",
    },
    {
        "name": "Chris Hemsworth",
        "followers": 90,
        "description": "Actor",
        "country": "Australia",
    },
    {
        "name": "Anushka Sharma",
        "followers": 65,
        "description": "Actress",
        "country": "India",
    },
    {
        "name": "Priyanka Chopra",
        "followers": 90,
        "description": "Actress & Producer",
        "country": "India",
    },
    {
        "name": "Shakira",
        "followers": 90,
        "description": "Singer",
        "country": "Colombia",
    },
    {
        "name": "Salman Khan",
        "followers": 65,
        "description": "Actor",
        "country": "India",
    },
    {
        "name": "Millie Bobby Brown",
        "followers": 65,
        "description": "Actress",
        "country": "UK",
    },
    {
        "name": "Will Smith",
        "followers": 65,
        "description": "Actor",
        "country": "USA",
    },
    {
        "name": "Kourtney Kardashian",
        "followers": 224,
        "description": "Media Personality",
        "country": "USA",
    },
    {"name": "Cardi B", "followers": 180, "description": "Rapper", "country": "USA"},
    {
        "name": "Bruno Mars",
        "followers": 75,
        "description": "Singer",
        "country": "USA",
    },
    {
        "name": "Gal Gadot",
        "followers": 100,
        "description": "Actress",
        "country": "Israel",
    },
    {
        "name": "MS Dhoni",
        "followers": 45,
        "description": "Cricketer",
        "country": "India",
    },
    {
        "name": "Park Jimin",
        "followers": 70,
        "description": "Singer (BTS)",
        "country": "South Korea",
    },
    {
        "name": "Keanu Reeves",
        "followers": 0,
        "description": "Actor",
        "country": "Canada",
    },
    {
        "name": "Doja Cat",
        "followers": 40,
        "description": "Rapper & Singer",
        "country": "USA",
    },
    {
        "name": "Johnny Depp",
        "followers": 35,
        "description": "Actor",
        "country": "USA",
    },
    {
        "name": "Charli D'Amelio",
        "followers": 50,
        "description": "TikToker & Dancer",
        "country": "USA",
    },
    {
        "name": "Tyler Blevins (Ninja)",
        "followers": 20,
        "description": "Streamer",
        "country": "USA",
    },
    {
        "name": "Suga",
        "followers": 65,
        "description": "Rapper (BTS)",
        "country": "South Korea",
    },
    # Additional 100 entries
    {
        "name": "Neymar Jr.",
        "followers": 220,
        "description": "Footballer",
        "country": "Brazil",
    },
    {
        "name": "Rihanna",
        "followers": 150,
        "description": "Singer & Businesswoman",
        "country": "Barbados",
    },
    {
        "name": "Kendall Jenner",
        "followers": 290,
        "description": "Model",
        "country": "USA",
    },
    {
        "name": "Nicki Minaj",
        "followers": 230,
        "description": "Rapper",
        "country": "USA",
    },
    {
        "name": "Miley Cyrus",
        "followers": 220,
        "description": "Singer & Actress",
        "country": "USA",
    },
    {
        "name": "Khloe Kardashian",
        "followers": 310,
        "description": "Media Personality",
        "country": "USA",
    },
    {
        "name": "Jennifer Lopez",
        "followers": 250,
        "description": "Singer & Actress",
        "country": "USA",
    },
    {
        "name": "Nicki Minaj",
        "followers": 230,
        "description": "Rapper",
        "country": "USA",
    },
    {
        "name": "Deepika Padukone",
        "followers": 75,
        "description": "Actress",
        "country": "India",
    },
    {
        "name": "Katrina Kaif",
        "followers": 70,
        "description": "Actress",
        "country": "India",
    },
    {
        "name": "Akshay Kumar",
        "followers": 70,
        "description": "Actor",
        "country": "India",
    },
    {
        "name": "Rohit Sharma",
        "followers": 35,
        "description": "Cricketer",
        "country": "India",
    },
    {
        "name": "Hardik Pandya",
        "followers": 25,
        "description": "Cricketer",
        "country": "India",
    },
    {
        "name": "Kylian Mbappé",
        "followers": 120,
        "description": "Footballer",
        "country": "France",
    },
    {
        "name": "Erling Haaland",
        "followers": 30,
        "description": "Footballer",
        "country": "Norway",
    },
    {
        "name": "Karim Benzema",
        "followers": 60,
        "description": "Footballer",
        "country": "France",
    },
    {
        "name": "Sergio Ramos",
        "followers": 55,
        "description": "Footballer",
        "country": "Spain",
    },
    {
        "name": "Luka Modrić",
        "followers": 15,
        "description": "Footballer",
        "country": "Croatia",
    },
    {
        "name": "Zlatan Ibrahimović",
        "followers": 60,
        "description": "Footballer",
        "country": "Sweden",
    },
    {
        "name": "Paulo Dybala",
        "followers": 50,
        "description": "Footballer",
        "country": "Argentina",
    },
    {
        "name": "Gareth Bale",
        "followers": 45,
        "description": "Footballer",
        "country": "Wales",
    },
    {
        "name": "Kevin De Bruyne",
        "followers": 20,
        "description": "Footballer",
        "country": "Belgium",
    },
    {
        "name": "Virgil van Dijk",
        "followers": 15,
        "description": "Footballer",
        "country": "Netherlands",
    },
    {
        "name": "Sadio Mané",
        "followers": 12,
        "description": "Footballer",
        "country": "Senegal",
    },
    {
        "name": "Mohamed Salah",
        "followers": 60,
        "description": "Footballer",
        "country": "Egypt",
    },
    {
        "name": "Robert Lewandowski",
        "followers": 30,
        "description": "Footballer",
        "country": "Poland",
    },
    {
        "name": "Harry Kane",
        "followers": 15,
        "description": "Footballer",
        "country": "England",
    },
    {
        "name": "Marcus Rashford",
        "followers": 18,
        "description": "Footballer",
        "country": "England",
    },
    {
        "name": "Jadon Sancho",
        "followers": 12,
        "description": "Footballer",
        "country": "England",
    },
    {
        "name": "Mason Mount",
        "followers": 8,
        "description": "Footballer",
        "country": "England",
    },
    {
        "name": "Jude Bellingham",
        "followers": 25,
        "description": "Footballer",
        "country": "England",
    },
    {
        "name": "Pedri",
        "followers": 15,
        "description": "Footballer",
        "country": "Spain",
    },
    {
        "name": "Gavi",
        "followers": 12,
        "description": "Footballer",
        "country": "Spain",
    },
    {
        "name": "Ansu Fati",
        "followers": 8,
        "description": "Footballer",
        "country": "Spain",
    },
    {
        "name": "Vinicius Jr.",
        "followers": 35,
        "description": "Footballer",
        "country": "Brazil",
    },
    {
        "name": "Rodrygo",
        "followers": 12,
        "description": "Footballer",
        "country": "Brazil",
    },
    {
        "name": "Casemiro",
        "followers": 8,
        "description": "Footballer",
        "country": "Brazil",
    },
    {
        "name": "Thiago Silva",
        "followers": 15,
        "description": "Footballer",
        "country": "Brazil",
    },
    {
        "name": "Alisson Becker",
        "followers": 12,
        "description": "Footballer",
        "country": "Brazil",
    },
    {
        "name": "Fabinho",
        "followers": 8,
        "description": "Footballer",
        "country": "Brazil",
    },
    {
        "name": "Philippe Coutinho",
        "followers": 25,
        "description": "Footballer",
        "country": "Brazil",
    },
    {
        "name": "Douglas Costa",
        "followers": 15,
        "description": "Footballer",
        "country": "Brazil",
    },
    {
        "name": "Marcelo",
        "followers": 55,
        "description": "Footballer",
        "country": "Brazil",
    },
    {
        "name": "Dani Alves",
        "followers": 40,
        "description": "Footballer",
        "country": "Brazil",
    },
    {
        "name": "Ronaldinho",
        "followers": 70,
        "description": "Former Footballer",
        "country": "Brazil",
    },
    {
        "name": "Kaká",
        "followers": 25,
        "description": "Former Footballer",
        "country": "Brazil",
    },
    {
        "name": "Pelé",
        "followers": 8,
        "description": "Former Footballer",
        "country": "Brazil",
    },
    {
        "name": "Rivaldo",
        "followers": 2,
        "description": "Former Footballer",
        "country": "Brazil",
    },
    {
        "name": "Roberto Carlos",
        "followers": 15,
        "description": "Former Footballer",
        "country": "Brazil",
    },
    {
        "name": "Cafu",
        "followers": 5,
        "description": "Former Footballer",
        "country": "Brazil",
    },
    {
        "name": "Romário",
        "followers": 3,
        "description": "Former Footballer",
        "country": "Brazil",
    },
    {
        "name": "Bebeto",
        "followers": 1,
        "description": "Former Footballer",
        "country": "Brazil",
    },
    {
        "name": "Francesco Totti",
        "followers": 12,
        "description": "Former Footballer",
        "country": "Italy",
    },
    {
        "name": "Andrea Pirlo",
        "followers": 8,
        "description": "Former Footballer",
        "country": "Italy",
    },
    {
        "name": "Franco Baresi",
        "followers": 2,
        "description": "Former Footballer",
        "country": "Italy",
    },
    {
        "name": "Paolo Maldini",
        "followers": 5,
        "description": "Former Footballer",
        "country": "Italy",
    },
    {
        "name": "Roberto Baggio",
        "followers": 3,
        "description": "Former Footballer",
        "country": "Italy",
    },
    {
        "name": "Gianluigi Buffon",
        "followers": 10,
        "description": "Footballer",
        "country": "Italy",
    },
    {
        "name": "Ciro Immobile",
        "followers": 5,
        "description": "Footballer",
        "country": "Italy",
    },
    {
        "name": "Lorenzo Insigne",
        "followers": 8,
        "description": "Footballer",
        "country": "Italy",
    },
    {
        "name": "Federico Chiesa",
        "followers": 6,
        "description": "Footballer",
        "country": "Italy",
    },
    {
        "name": "Nicolo Barella",
        "followers": 4,
        "description": "Footballer",
        "country": "Italy",
    },
    {
        "name": "Marco Verratti",
        "followers": 5,
        "description": "Footballer",
        "country": "Italy",
    },
    {
        "name": "Ciro Immobile",
        "followers": 5,
        "description": "Footballer",
        "country": "Italy",
    },
    {
        "name": "Thierry Henry",
        "followers": 8,
        "description": "Former Footballer",
        "country": "France",
    },
    {
        "name": "Zinedine Zidane",
        "followers": 5,
        "description": "Former Footballer",
        "country": "France",
    },
    {
        "name": "Michel Platini",
        "followers": 1,
        "description": "Former Footballer",
        "country": "France",
    },
    {
        "name": "Didier Drogba",
        "followers": 15,
        "description": "Former Footballer",
        "country": "Ivory Coast",
    },
    {
        "name": "Samuel Eto'o",
        "followers": 8,
        "description": "Former Footballer",
        "country": "Cameroon",
    },
    {
        "name": "Yaya Touré",
        "followers": 5,
        "description": "Former Footballer",
        "country": "Ivory Coast",
    },
    {
        "name": "Riyad Mahrez",
        "followers": 12,
        "description": "Footballer",
        "country": "Algeria",
    },
    {
        "name": "Hakim Ziyech",
        "followers": 8,
        "description": "Footballer",
        "country": "Morocco",
    },
    {
        "name": "Achraf Hakimi",
        "followers": 15,
        "description": "Footballer",
        "country": "Morocco",
    },
    {
        "name": "Youssef En-Nesyri",
        "followers": 3,
        "description": "Footballer",
        "country": "Morocco",
    },
    {
        "name": "Sofiane Boufal",
        "followers": 2,
        "description": "Footballer",
        "country": "Morocco",
    },
    {
        "name": "Mehdi Benatia",
        "followers": 5,
        "description": "Former Footballer",
        "country": "Morocco",
    },
    {
        "name": "Jay-Z",
        "followers": 8,
        "description": "Rapper & Businessman",
        "country": "USA",
    },
    {
        "name": "Drake",
        "followers": 145,
        "description": "Rapper",
        "country": "Canada",
    },
    {
        "name": "Eminem",
        "followers": 35,
        "description": "Rapper",
        "country": "USA",
    },
    {
        "name": "Kanye West",
        "followers": 18,
        "description": "Rapper & Fashion Designer",
        "country": "USA",
    },
    {
        "name": "Travis Scott",
        "followers": 55,
        "description": "Rapper",
        "country": "USA",
    },
    {
        "name": "Lil Wayne",
        "followers": 25,
        "description": "Rapper",
        "country": "USA",
    },
    {
        "name": "Snoop Dogg",
        "followers": 80,
        "description": "Rapper",
        "country": "USA",
    },
    {
        "name": "50 Cent",
        "followers": 30,
        "description": "Rapper",
        "country": "USA",
    },
    {
        "name": "Kendrick Lamar",
        "followers": 20,
        "description": "Rapper",
        "country": "USA",
    },
    {
        "name": "J. Cole",
        "followers": 15,
        "description": "Rapper",
        "country": "USA",
    },
    {
        "name": "Future",
        "followers": 22,
        "description": "Rapper",
        "country": "USA",
    },
    {
        "name": "Lil Baby",
        "followers": 28,
        "description": "Rapper",
        "country": "USA",
    },
    {
        "name": "DaBaby",
        "followers": 18,
        "description": "Rapper",
        "country": "USA",
    },
    {
        "name": "Megan Thee Stallion",
        "followers": 32,
        "description": "Rapper",
        "country": "USA",
    },
    {
        "name": "Lil Nas X",
        "followers": 15,
        "description": "Rapper",
        "country": "USA",
    },
    {
        "name": "Roddy Ricch",
        "followers": 12,
        "description": "Rapper",
        "country": "USA",
    },
    {
        "name": "Pop Smoke",
        "followers": 8,
        "description": "Rapper",
        "country": "USA",
    },
    {
        "name": "Juice WRLD",
        "followers": 15,
        "description": "Rapper",
        "country": "USA",
    },
    {
        "name": "XXXTentacion",
        "followers": 25,
        "description": "Rapper",
        "country": "USA",
    },
    {
        "name": "Lil Uzi Vert",
        "followers": 18,
        "description": "Rapper",
        "country": "USA",
    },
    {
        "name": "Playboi Carti",
        "followers": 12,
        "description": "Rapper",
        "country": "USA",
    },
    {
        "name": "21 Savage",
        "followers": 15,
        "description": "Rapper",
        "country": "USA",
    },
    {
        "name": "Offset",
        "followers": 20,
        "description": "Rapper",
        "country": "USA",
    },
    {
        "name": "Quavo",
        "followers": 18,
        "description": "Rapper",
        "country": "USA",
    },
    {
        "name": "Takeoff",
        "followers": 8,
        "description": "Rapper",
        "country": "USA",
    },
    {
        "name": "Migos",
        "followers": 25,
        "description": "Rap Group",
        "country": "USA",
    },
    {
        "name": "A$AP Rocky",
        "followers": 18,
        "description": "Rapper",
        "country": "USA",
    },
    {
        "name": "Tyler, The Creator",
        "followers": 12,
        "description": "Rapper",
        "country": "USA",
    },
    {
        "name": "Frank Ocean",
        "followers": 5,
        "description": "Singer",
        "country": "USA",
    },
    {
        "name": "SZA",
        "followers": 15,
        "description": "Singer",
        "country": "USA",
    },
    {
        "name": "The Weeknd",
        "followers": 35,
        "description": "Singer",
        "country": "Canada",
    },
    {
        "name": "Dua Lipa",
        "followers": 88,
        "description": "Singer",
        "country": "UK",
    },
    {
        "name": "Adele",
        "followers": 42,
        "description": "Singer",
        "country": "UK",
    },
    {
        "name": "Ed Sheeran",
        "followers": 45,
        "description": "Singer",
        "country": "UK",
    },
    {
        "name": "Sam Smith",
        "followers": 12,
        "description": "Singer",
        "country": "UK",
    },
    {
        "name": "Harry Styles",
        "followers": 48,
        "description": "Singer",
        "country": "UK",
    },
    {
        "name": "Niall Horan",
        "followers": 32,
        "description": "Singer",
        "country": "Ireland",
    },
    {
        "name": "Zayn Malik",
        "followers": 45,
        "description": "Singer",
        "country": "UK",
    },
    {
        "name": "Louis Tomlinson",
        "followers": 18,
        "description": "Singer",
        "country": "UK",
    },
    {
        "name": "Liam Payne",
        "followers": 22,
        "description": "Singer",
        "country": "UK",
    },
    {
        "name": "Shawn Mendes",
        "followers": 68,
        "description": "Singer",
        "country": "Canada",
    },
    {
        "name": "Camila Cabello",
        "followers": 65,
        "description": "Singer",
        "country": "USA",
    },
    {
        "name": "Halsey",
        "followers": 25,
        "description": "Singer",
        "country": "USA",
    },
    {
        "name": "Lorde",
        "followers": 8,
        "description": "Singer",
        "country": "New Zealand",
    },
    {
        "name": "Lana Del Rey",
        "followers": 20,
        "description": "Singer",
        "country": "USA",
    },
]
